kind: pipeline
type: docker
name: default
trigger:
  branch:
    #- dev
    - master
steps:
  - name: build_push
    image: docker:dind
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PWD:
        from_secret: DOCKER_PWD
    commands:
      - docker --version
      - docker login -u "$DOCKER_USER" -p "$DOCKER_PWD".    # login to docker hub
      - docker buildx create --name aBuildX --use      # Create and use a Buildx builder
      - docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t hao88/pkms:amd64 -t hao88/pkms:arm64 --push . # Build and push multi-arch images
      - docker buildx rm aBuildX  # Remove the Buildx builder
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
