kind: pipeline
type: docker
name: default
trigger:
  branch:
    - dev
    - main
    - rbac-domains
    - Single
steps:
  - name: docker-build_push
    image: docker:dind
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PWD:
        from_secret: DOCKER_PWD
    commands:
      - docker --version
      - docker stop pkms || true
      - docker rm pkms || true
      # 清理旧镜像
      - docker images | grep 'hao88/pkms' | awk '{print $3}' | xargs -r docker rmi -f
      # - docker login -u "$DOCKER_USER" -p "$DOCKER_PWD".    # login to docker hub
      - echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin
      - docker buildx create --name aBuildX --use      # Create and use a Buildx builder
      #- docker buildx build --platform linux/amd64 -f Dockerfile -t hao88/pkms:amd64 --push . # Build and push multi-arch images
      - docker buildx build --platform linux/amd64 -f Dockerfile -t hao88/pkms:amd64 . # Build only
      - docker buildx rm aBuildX  # Remove the Buildx builder
      - docker run -d --name pkms --restart unless-stopped -p 65080:8080 hao88/pkms:amd64
      # 检查容器状态
      - docker ps | grep pkms

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
