kind: pipeline
type: docker
name: default
trigger:
  branch:
    - dev
    - main
    - rbac-domains
    - Single
    - pgsql
node:
  runner: n305
steps:
  - name: all_in_docker
    image: docker:dind
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PWD:
        from_secret: DOCKER_PWD
    commands:
      - docker --version
      - docker stop pkms || true # 停止旧容器
      - docker rm pkms || true   # 删除旧容器
      - docker images | grep 'hao88' | awk '{print $3}' | xargs -r -I{} sh -c 'docker rmi -f {} || true'  # 清理旧镜像
      - docker images | grep '52927295' | awk '{print $3}' | xargs -r -I{} sh -c 'docker rmi -f {} || true'  # 清理旧镜像
      - echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER" --password-stdin
      - docker buildx create --name aBuildX --use      # Create and use a Buildx builder
      - docker buildx build --platform linux/amd64 -f Dockerfile -t hao88/pkms:rolling --push . # Build and push multi-arch images
      - docker buildx rm aBuildX  # Remove the Buildx builder
      - docker run -d --name pkms --restart unless-stopped -p 65080:65080 -v /mnt/temporary/test/pkms/database:/app/database -v /mnt/temporary/test/pkms/uploads:/app/uploads -v /mnt/temporary/test/pkms/logs:/app/logs hao88/pkms:rolling
      - docker ps | grep pkms # 检查容器状态

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
