version: 1

before:
  hooks:
    - go generate ./...
    - npm ci --prefix frontend
    - npm run build --prefix frontend

builds:
  - main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

dockers:
  - image_templates:
      - "docker.io/hao88/pkms:{{ .Tag }}"
      - "docker.io/hao88/pkms:latest"
    dockerfile: DockerfileGoReleaser
    use: buildx
    skip_push: false
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--progress=plain"
      - "--no-cache"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"