services:
  pkms:
    image: hao88/pkms:latest
    container_name: pkms
    ports:
      - "65080:65080"
    environment:
      - NODE_ENV=production
    volumes:
      - /mnt/user/appdata/data.db:/app/data.db
      - /mnt/user/appdata/logs:/app/logs
      - /mnt/user/appdata/uploads:/app/uploads