services:
  pkms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pkms
    ports:
      - "55173:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped